---
- name: check if config secret already exists
  command: docker secret inspect {{ service_name_altered }}-config
  register: secret_exists
  ignore_errors: True

- name: remove secret if it already exists
  command: docker secret rm {{ service_name_altered }}-config
  when: secret_exists is succeeded and config_changed.changed

- name: create secret from service config file
  command: docker secret create {{ service_name_altered }}-config {{ service_config_dir }}/{{ service_name_altered }}.{{ service_config_format }}
  when: secret_exists is failed or config_changed.changed
