---
- name: include provision config
  include_vars: "{{ ansible_dir }}/../provision-config.yml"

- name: include globals
  include_vars: globals.yml

- name: check existence provision-config.override.yml
  local_action: stat path={{ environment_dir }}/provision-config.override.yml
  changed_when: False
  become: no
  register: provision_config_override

- name: vars - include 'provision-config.override.yml'
  include_vars: "{{ environment_dir }}/provision-config.override.yml"
  when: provision_config_override.stat.exists
